language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - sudo apt-get -y install libxml2-utils openssl
  - rustup target add wasm32-unknown-unknown

before_script:
  - cargo generate-lockfile

script:
  - cargo check --verbose --workspace
  - cargo test --verbose --workspace
  - cargo check --verbose --workspace --target wasm32-unknown-unknown
