[package]
name = "promi"
version = "0.0.0"
authors = ["0b11001111"]
edition = "2018"
description = "Process Mining for Rust"
readme = "README.md"
repository = "https://github.com/PM4Rs/promi"
license = "MIT OR Apache-2.0"
keywords = ["processmining", "datamining", "streaming"]


[dependencies]


[profile.release]
panic = 'abort'
